Yang Set Packing
CharJon/GeCO pull request #31
Opened 2020-11-17 14:56 UTC by mmghannam

2020-11-18 10:41 UTC, mmghannam commented
This is still missing the simple instance test. I am changing it to a draft PR.

2020-11-25 17:02 UTC, CharJon requested changes

2020-11-25 17:02 UTC, CharJon commented on geco/mips/set_packing.py
> +    nonzero_vars_for_constraint = [
I think we should name this num_nonzero...

2020-11-25 17:02 UTC, CharJon commented on geco/mips/set_packing.py
> +    costs = [seed.randint(1, 100) for _ in range(n)]
randint(1, 100+1)

2020-11-25 17:02 UTC, CharJon commented on geco/mips/set_packing.py
> +        seed.randint(2 * n // 25 + 1, 3 * n // 25 - 1) for _ in range(m)
randint(2 * n // 25 + 1, 3 * n // 25 - 1 + 1)

2020-11-30 10:53 UTC, merged